// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWji83GOVjX4vhOGxG79RiZu10iFNfFOo',
    appId: '1:1014182966961:web:a16c533230d7dde997d490',
    messagingSenderId: '1014182966961',
    projectId: 'cravecrush-8f5c6',
    authDomain: 'cravecrush-8f5c6.firebaseapp.com',
    storageBucket: 'cravecrush-8f5c6.appspot.com',
    measurementId: 'G-N1XD4JR2RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60AAOl2n61hOTKG-FVkKt2wnYe149wDY',
    appId: '1:1014182966961:android:a2cf74362811cbb497d490',
    messagingSenderId: '1014182966961',
    projectId: 'cravecrush-8f5c6',
    storageBucket: 'cravecrush-8f5c6.appspot.com',
  );
}
